sudo: false
language: python

env:
  - PYTHON_VERSION=3.6
  
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --q --y conda 

install:
  - conda install --yes python=$PYTHON_VERSION pip # numpy pandas scipy scikit-learn statsmodels theano keras tensorflow nose
  - pip install coverage
  - pip install coveralls
  - pip install nose
  - pip install boto3
  #- pip install
  #- pip install sklearn matplotlib pydot dill pathos sqlalchemy #PyAF deppendencies along with scipy and pandas
  #- pip install --upgrade git+git://github.com/antoinecarme/pyaf.git #PyAF
  #- pip install pyaf
  #- pip install --upgrade git+git://github.com/influxdata/influxdb-python.git #InfluxDB
  #- pip install influxdb
  
script:
  - python main.py
  #- nosetests --verbose --with-coverage --cover-package=tests

after_success:
  - coveralls

notifications:
    slack: cpacketprojectteam:YPF8UW0x4mmEpGHOtWJ6oJx3
    email: false
